version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/projects/health-app/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/projects/reactive-forms/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"
      include: "scope"
