[build]
  base = ""
  command = "ng build --project=health-app"
  publish = "projects/health-app/dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
